### PR TITLE
Skip the first split delta on rewrite

### LINKED ISSUE #337: A infinite loop caused by epoch not match
When run commands: 
```
RUST_BACKTRACE=1 RUST_LOG=debug cargo run -p photondb-tools -- stress --db /tmp/photondb --destory-db false   2>&1 | tee log
```

The tools is loop infinitely. However, the binary is generated by a local modified patch, so it may not be reproduced by the master version. I will record some conclusions from the analysis here. If you encounter similar cases later, you can refer to it.

### PR DESCRIPTION
**Pull request by huachaohuang**
Closes #337

### CODE REVIEW

File: photondb/src/tree/mod.rs [hunk 1]
```diff
@@ -732,16 +705,109 @@ impl<'a, E: Env> TreeTxn<'a, E> {
...
+        })
+        .await?;
+
+        // Merge the delta pages.
+        let iter = MergingPageIter::new(builder.build(), range_limit);
+        let builder = SortedPageBuilder::new(old_page.tier(), PageKind::Data).with_iter(iter);
+        let mut txn = self.guard.begin().await;
+        let (mut new_addr, mut new_page) = txn.alloc_page(builder.size()).await?;
+        builder.build(&mut new_page);
+        new_page.set_epoch(old_page.epoch());
```
Comment (w41ter) [inline photondb/src/tree/mod.rs:783]: It seems that the `page_id` of `new_page` isn't set, so the program is going to panics if rewriting the `new_page`.

**Review by w41ter — APPROVED** [review]
