### PR TITLE
page_store: fix read empty data block

### LINKED ISSUE #305: read page file panic when data segment is empty
```
rust_panic (@rust_panic:7)
std::panicking::rust_panic_with_hook (@std::panicking::rust_panic_with_hook:112)
std::panicking::begin_panic_handler::{{closure}} (@std::panicking::begin_panic_handler::{{closure}}:40)
std::sys_common::backtrace::__rust_end_short_backtrace (@std::sys_common::backtrace::__rust_end_short_backtrace:10)
rust_begin_unwind (@rust_begin_unwind:30)
core::panicking::panic_fmt (@core::panicking::panic_fmt:13)
core::panicking::panic (@core::panicking::panic:16)
photondb::page_store::page_file::file_builder::AlignBuffer::new (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/file_builder.rs:560)
photondb::page_store::page_file::file_reader::PageFileReader<R>::read_exact_at::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/file_reader.rs:43)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
photondb::page_store::page_file::file_reader::MetaReader<R>::read_index_block::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/file_reader.rs:165)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:28)
photondb::page_store::page_file::file_reader::MetaReader<R>::read_file_meta::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/file_reader.rs:95)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:28)
photondb::page_store::page_file::file_reader::MetaReader<R>::open::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/file_reader.rs:114)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:28)
photondb::page_store::page_file::facade::PageFiles<E>::open_meta_reader::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/page_file/mod.rs:170)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:28)
photondb::page_store::jobs::reclaim::ReclaimCtx<E,R>::rewrite_file_impl::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/jobs/reclaim.rs:162)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
photondb::page_store::jobs::reclaim::ReclaimCtx<E,R>::rewrite_file::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/jobs/reclaim.rs:154)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
photondb::page_store::jobs::reclaim::ReclaimCtx<E,R>::rewrite_files::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/jobs/reclaim.rs:121)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
photondb::page_store::jobs::reclaim::ReclaimCtx<E,R>::reclaim::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/jobs/reclaim.rs:86)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
photondb::page_store::jobs::reclaim::ReclaimCtx<E,R>::run::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/page_store/jobs/reclaim.rs:72)
<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (@<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll:22)
futures_executor::local_pool::block_on::{{closure}} (/home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-executor-0.3.25/src/local_pool.rs:317)
futures_executor::local_pool::run_executor::{{closure}} (/home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-executor-0.3.25/src/local_pool.rs:90)
std::thread::local::LocalKey<T>::try_with (@std::thread::local::LocalKey<T>::try_with:66)
std::thread::local::LocalKey<T>::with (@std::thread::local::LocalKey<T>::with:7)
futures_executor::local_pool::run_executor (/home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-executor-0.3.25/src/local_pool.rs:86)
futures_executor::local_pool::block_on (/home/robi/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/futures-executor-0.3.25/src/local_pool.rs:317)
<photondb::env::stdenv::Std as photondb::env::Env>::spawn_background::{{closure}} (/home/robi/Code/rust/photondb/photondb/src/env/stdenv.rs:45)
std::sys_common::backtrace::__rust_begin_short_backtrace (@std::sys_common::backtrace::__rust_begin_short_backtrace:10)
std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}} (@std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}:10)
<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (@<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once:10)
std::panicking::try::do_call (@std::panicking::try::do_call:35)
__rust_try (@__rust_try:10)
std::panicking::try (@std::panicking::try:28)
std::panic::catch_unwind (@std::panic::catch_unwind:10)
std::thread::Builder::spawn_unchecked_::{{closure}} (@std::thread::Builder::spawn_unchecked_::{{closure}}:83)
core::ops::function::FnOnce::call_once{{vtable.shim}} (@core::ops::function::FnOnce::call_once{{vtable.shim}}:6)
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once (@std::sys::unix::thread::Thread::new::thread_start:15)
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once (@std::sys::unix::thread::Thread::new::thread_start:13)
std::sys::unix::thread::Thread::new::thread_start (@std::sys::unix::thread::Thread::new::thread_start:11)
start_thread (@start_thread:48)
__clone (@__clone:26)
```

### PR DESCRIPTION
**Pull request by zojw**
closes #305

### CODE REVIEW

File: photondb/src/page_store/page_file/file_reader.rs [hunk 1]
```diff
@@ -118,18 +119,26 @@ impl<R: PositionalReader> MetaReader<R> {
...
-        self.reader
-            .read_exact_at(&mut buf, page_table_offset)
-            .await
-            .expect("read page table meta page fail");
+        let buf = if page_table_len == 0 {
+            vec![]
+        } else {
+            let mut buf = vec![0u8; page_table_len];
+            self.reader
+                .read_exact_at(&mut buf, page_table_offset)
```
Comment (huachaohuang) [inline photondb/src/page_store/page_file/file_reader.rs:127]: Can we handle the case of reading zero-length data inside the reader? Then we don't need to handle this case everywhere.

**Review by huachaohuang — APPROVED** [review]
