### PR TITLE
Fix leaf and inner iter rewind

### LINKED ISSUE #285: key may be lost
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some([0, 0, 0, 0, 0, 0, 0, 0])`', photondb/src/lib.rs:81:9
stack backtrace:
[2022-11-16T08:06:25Z INFO  photondb::page_store::jobs::reclaim] Rewrite file 15 with 605 active pages, 0 dealloc pages, relocate 31165 bytes, free 55440 bytes, free ratio 0.6401, latest 17691 microseconds
   0: rust_begin_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:181:5
   4: photondb::tests::must_get::{{closure}}
             at ./src/lib.rs:81:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::tests::crud::{{closure}}
             at ./src/lib.rs:95:44
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:54
   9: tokio::coop::with_budget::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/thread/local.rs:446:16
  11: std::thread::local::LocalKey<T>::with
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/thread/local.rs:422:9
  12: tokio::coop::with_budget
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
  13: tokio::coop::budget
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  14: tokio::park::thread::CachedParkThread::block_on
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  15: tokio::runtime::enter::Enter::block_on
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/enter.rs:152:13
```

_Originally posted by @w41ter in https://github.com/photondb/photondb/issues/284#issuecomment-1316547628_

### PR DESCRIPTION
**Pull request by w41ter**
Closes #285.

### CODE REVIEW

**Review by huachaohuang — APPROVED** [review]
Hmm, why do I remember that I already fixed this before 😢

File: photondb/src/tree/page.rs [hunk 1]
```diff
@@ -191,6 +191,7 @@ impl<'a> Iterator for MergingLeafPageIter<'a> {
 impl<'a> RewindableIterator for MergingLeafPageIter<'a> {
     fn rewind(&mut self) {
         self.iter.rewind();
+        self.last_raw = None;
```
Comment (huachaohuang) [inline photondb/src/tree/page.rs:194]: The `self.skip_same_raw` should also be reset. I think I lost a commit or something.

**Review by huachaohuang — APPROVED** [review]
